version: "3.4"

services:
    web: 
        container_name: fichademusicosccbapi
        image: fichademusicosccbapi
        environment:
          - PORT=5000
        ports:
          - 5000:5000
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
          - db
        networks: 
          - fichademusicosccb-network
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: "d32vc51ps6"
          ACCEPT_EULA: "Y"
        networks: 
          - fichademusicosccb-network
networks:
  fichademusicosccb-network:
    driver: bridge

